// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint3.Data;

#nullable disable

namespace Sprint3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420140827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sprint3.Models.Cartao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ideCartao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("stsAtivo");

                    b.Property<long?>("ContaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ideConta");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtcCriacao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtcVencimento");

                    b.Property<int>("Limite")
                        .HasColumnType("int")
                        .HasColumnName("nroLimite");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nroCartao");

                    b.Property<string>("TipoCartao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("selCartao");

                    b.Property<int>("Via")
                        .HasColumnType("int")
                        .HasColumnName("nroVia");

                    b.HasKey("Id");

                    b.ToTable("cartoes");
                });

            modelBuilder.Entity("Sprint3.Models.Cliente", b =>
                {
                    b.Property<long>("IdeCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ideCliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdeCliente"));

                    b.Property<DateTime>("DtcNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtcNascimento");

                    b.Property<string>("NomCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomCliente");

                    b.Property<string>("NomEndereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomEndereco");

                    b.Property<string>("NroCPF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nroCPF");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("longtext")
                        .HasColumnName("senhaHash");

                    b.Property<bool>("StsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("stsAtivo");

                    b.HasKey("IdeCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Sprint3.Models.Conta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ideConta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("stsAtivo");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ideCliente");

                    b.Property<double>("Saldo")
                        .HasColumnType("double")
                        .HasColumnName("nroSaldo");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("selConta");

                    b.HasKey("Id");

                    b.ToTable("contas");
                });

            modelBuilder.Entity("Sprint3.Models.Transacao", b =>
                {
                    b.Property<long>("IdeTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ideTransacao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdeTransacao"));

                    b.Property<DateTime>("DtcTransacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtcTransacao");

                    b.Property<long?>("IdeContaFinal")
                        .HasColumnType("bigint")
                        .HasColumnName("ideContaFinal");

                    b.Property<long?>("IdeContaOrigem")
                        .HasColumnType("bigint")
                        .HasColumnName("ideContaOrigem");

                    b.Property<double>("NroValor")
                        .HasColumnType("double")
                        .HasColumnName("nroValor");

                    b.Property<string>("SelTransacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("selTransacao");

                    b.HasKey("IdeTransacao");

                    b.ToTable("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
